#管理员
CREATE TABLE m_admin(
  id INT PRIMARY KEY AUTO_INCREMENT,
  account VARCHAR(100) UNIQUE NOT NULL DEFAULT '',
  password VARCHAR(100) NOT NULL DEFAULT '',
  name VARCHAR(100) NOT NULL DEFAULT ''
)ENGINE = MyISAM DEFAULT CHARSET = utf8 COMMENT '管理员';

CREATE TABLE m_goods(
  id INT PRIMARY KEY AUTO_INCREMENT,
  gname VARCHAR(100) NOT NULL DEFAULT '' COMMENT '商品名称',
  originPrice DECIMAL(5,2) NOT NULL DEFAULT 0.00 COMMENT '原价',
  vipPrice DECIMAL(5,2) NOT NULL DEFAULT 0.00 COMMENT '会员价',
  imgUrls VARCHAR(200) NOT NULL DEFAULT '' COMMENT '商品图片',
  profile text NOT NULL DEFAULT '' COMMENT '商品介绍',
  status TINYINT(1) NOT NULL DEFAULT 0 COMMENT '0下架 1上架',
  creatTime INT NOT NULL DEFAULT 0 ,
  updateTime INT NOT NULL DEFAULT 0
)ENGINE = MyISAM DEFAULT CHARSET = utf8 COMMENT '商品';

CREATE TABLE m_cart (
  id INT PRIMARY KEY AUTO_INCREMENT,
  gid INT NOT NULL DEFAULT 0 COMMENT '商品id',
  uid INT NOT NULL DEFAULT 0 COMMENT '用户id',
  gnum INT(3) NOT NULL DEFAULT '' COMMENT '数量',
  amount DECIMAL(6,2) NOT NULL DEFAULT 0.00 COMMENT '总价',
  status TINYINT(1) NOT NULL DEFAULT 1 COMMENT '0 已删除 1正常',
  creatTime INT NOT NULL DEFAULT 0 ,
  updateTime INT NOT NULL DEFAULT 0,
  KEY uid(uid),
  KEY gid(gid)
)ENGINE=MyISAM DEFAULT CHARSET=UTF8 COMMENT '购物车';

CREATE TABLE m_order (
  id INT PRIMARY KEY AUTO_INCREMENT,
  uid INT NOT NULL DEFAULT 0 COMMENT '用户id',
  did INT NOT NULL DEFAULT 0 COMMENT '详情id',
  addressId INT NOT NULL DEFAULT 0 COMMENT '收货地址',
  orderSn VARCHAR(100) NOT NULL DEFAULT '' COMMENT '订单号',
  amount DECIMAL(8,2) NOT NULL DEFAULT 0.00 COMMENT '总金额',
  noPostage TINYINT(1) NOT NULL DEFAULT 1 COMMENT '0不包邮 1包邮',
  payType VARCHAR(100) NOT NULL DEFAULT '' COMMENT '付款方式',
  courier VARCHAR(200) NOT NULL DEFAULT '' COMMENT '快递号',
  status TINYINT(1) NOT NULL DEFAULT 0 COMMENT '0未发货 1已发货 2已完成',
  creatTime INT NOT NULL DEFAULT 0 ,
  updateTime INT NOT NULL DEFAULT 0,
  KEY uid(uid),
  KEY orderSn(orderSn),
  KEY did(did)
)ENGINE=innodb DEFAULT CHARSET=UTF8 COMMENT '订单';

CREATE TABLE m_detail (
  id INT PRIMARY KEY AUTO_INCREMENT,
  oid INT NOT NULL DEFAULT 0 COMMENT '订单id',
  gid INT NOT NULL DEFAULT 0 COMMENT '商品id',
  gnum INT(5) NOT NULL DEFAULT 0 COMMENT '商品数量',
  gAmount DECIMAL(5,2) NOT NULL DEFAULT 0.00 COMMENT '总价',
  KEY oid(oid),
  KEY gid(gid)
)ENGINE=MyISAM DEFAULT CHARSET=UTF8 COMMENT '订单详情';

CREATE TABLE m_user (
  id INT PRIMARY KEY AUTO_INCREMENT,
  pid INT NOT NULL DEFAULT 0 COMMENT '上级id',
  uname VARCHAR(100) NOT NULL DEFAULT ''COMMENT '用户姓名',
  password VARCHAR(100) NOT NULL DEFAULT '' COMMENT '密码',
  secondaryPassword VARCHAR(100) NOT NULL DEFAULT '' COMMENT '二级密码',
  phone VARCHAR(20) NOT NULL DEFAULT '' COMMENT '手机号',
  imgUrl VARCHAR(100) NOT NULL DEFAULT '' COMMENT '头像',
  balance DECIMAL(8,2) NOT NULL DEFAULT 0.00 COMMENT '可用余额',
  extensionCode VARCHAR(200) NOT NULL DEFAULT '' COMMENT '推广码',
  amount DECIMAL(8,2) NOT NULL DEFAULT 0.00 COMMENT '总佣金',
  level TINYINT(1) NOT NULL DEFAULT 1 COMMENT '会员等级',
  aliAccount VARCHAR(100) NOT NULL DEFAULT '' COMMENT '支付宝账号',
  status TINYINT(1) NOT NULL DEFAULT 0 COMMENT '0未激活 1已激活',
  creatTime INT NOT NULL DEFAULT 0 ,
  updateTime INT NOT NULL DEFAULT 0
)ENGINE=MyISAM DEFAULT CHARSET=UTF8 COMMENT '用户';

CREATE TABLE m_address (
  id INT PRIMARY KEY AUTO_INCREMENT,
  uid INT NOT NULL DEFAULT 0 COMMENT '用户',
  consignee VARCHAR(100) NOT NULL DEFAULT '' COMMENT '收货人',
  consigneePhone VARCHAR(20) NOT NULL DEFAULT '' COMMENT '收货人电话',
  address VARCHAR(250) NOT NULL DEFAULT '' COMMENT '收货地址',
  creatTime INT NOT NULL DEFAULT 0 ,
  updateTime INT NOT NULL DEFAULT 0,
  KEY uid(uid)
)ENGINE=MyISAM DEFAULT CHARSET=UTF8 COMMENT '收货地址';

CREATE TABLE m_achievement (
  id INT PRIMARY KEY AUTO_INCREMENT,
  refereeId INT NOT NULL DEFAULT 0 COMMENT '推荐人',
  uid INT NOT NULL DEFAULT 0 COMMENT '被推荐人',
  payAmount DECIMAL(5,2) NOT NULL DEFAULT 0.00 COMMENT '被推荐人应支付金额',
  refereeObtain DECIMAL(5,2) NOT NULL DEFAULT 0.00 COMMENT '推荐人可获得佣金',
  isDirect TINYINT(1) NOT NULL DEFAULT 1 COMMENT '0 不是直推人 1是直推人',
  status TINYINT(1) NOT NULL DEFAULT 0 COMMENT '0待确认付款 1已确认付款',
  creatTime INT NOT NULL DEFAULT 0 ,
  updateTime INT NOT NULL DEFAULT 0,
  KEY uid(uid)
)ENGINE=MyISAM DEFAULT CHARSET=UTF8 COMMENT '推广业绩';

CREATE TABLE m_consumption (
  id INT PRIMARY KEY AUTO_INCREMENT,
  oid INT NOT NULL DEFAULT 0 COMMENT '订单id',
  uid INT NOT NULL DEFAULT 0 COMMENT '推荐人',
  consumptionObtain DECIMAL(5,2) NOT NULL DEFAULT 0.00 COMMENT '消费佣金',
  isDirect TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否直推 0不是 1是',
  status TINYINT(1) NOT NULL DEFAULT 0 COMMENT '0待确认付款 1已确认付款',
  creatTime INT NOT NULL DEFAULT 0 ,
  updateTime INT NOT NULL DEFAULT 0,
  KEY uid(uid)
)ENGINE=MyISAM DEFAULT CHARSET=UTF8 COMMENT '消费业绩';


#定义常量

#  会员等级对应金额
# LEVEL_ONE => 1600
# LEVEL_TWO => 3200
# LEVEL_THREE => 4800

#  会员等级对应直推金额上限
# UPPER_LIMIT_ONE => LEVEL_ONE*25%
# UPPER_LIMIT_TWO => LEVEL_TWO*25%
# UPPER_LIMIT_THREE => LEVEL_THREE*25%

#  邮费 POSTAGE => 25

# 推广分级佣金设置 PARENT_ONE => 25%  PARENT_TWO => 10%  PARENT_THREE =>5%





